# Generated by Django 4.2.5 on 2023-09-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_rename_subsriber_id_subscriber_subscriber_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('email_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRequestItem',
            fields=[
                ('email_request_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.emailrequest')),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriber')),
            ],
        ),
    ]
